import type { Metadata } from "next";
import "./globals.css";
import {
	ClerkProvider,
	Show,
	SignInButton,
	SignUpButton,
	UserButton,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Outfit } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";

const outfit = Outfit({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-outfit",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`dark ${outfit.className}`}
			suppressHydrationWarning
		>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					disableTransitionOnChange
				>
					<ClerkProvider appearance={{ baseTheme: dark }}>
						<header className="flex justify-end items-center p-4 gap-4 h-16">
							<Show when="signed-out">
								<SignInButton />
								<SignUpButton>
									<Button className="bg-purple-700 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
										Sign Up
									</Button>
								</SignUpButton>
							</Show>
							<Show when="signed-in">
								<UserButton />
							</Show>
						</header>

						{children}
					</ClerkProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
